[package]
name = "cuby"
version = "0.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1.5", features = ["fltk-bundled"] }
minreq = { version = "2.13.4", features = ["https-rustls-probe"] }
rust-embed="8.7.0"
anitomy = "0.2.0"
rfd = "0.15.3"
miniserde = "0.1.42"

[build-dependencies]
embed-resource = "3.0.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
