[package]
name = "cuby"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["icon"]
icon = []


[dependencies]
miniserde = "0.1.45"

[target.'cfg(not(windows))'.dependencies]
fltk = { version = "1.5.22", default-features = false, features = [
    "fltk-bundled",
    "single-threaded"
] }
native-tls = { version = "0.2.14", default-features = true }

[target.'cfg(windows)'.dependencies]
fltk = { version = "1.5.22", default-features = false, features = [
    "fltk-bundled",
    "no-gdiplus",
    "no-pango",
    "single-threaded"
] }
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_System_Registry", "Win32_Networking_WinHttp"] }

[build-dependencies]
embed-resource = "3.0.6"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false
debug = false
incremental = false
