[package]
name = "cuby"
version = "0.3.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk =  "^1.5"
clap = { version = "^4.0", features = ["derive"] }
miniserde = "^0.1"
minreq = { version = "^2", features = ["https-rustls-probe"] }
urlencoding = "^2.1"
webbrowser = "1.0.4"
winreg = "0.55.0"
natord = "^1.0"
uuid = { version = "^1.0", features = ["v4"] }
regex = "1.11.1"
chrono = "0.4.41"

[build-dependencies]
embed-resource = "3.0.2"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
